### ISSUE TITLE
kubectl apply --dry-run=server & kubectl diff generate "Update of Deployment" messages

### ISSUE THREAD

**Issue by vtrubesset** [numberly/kubemen#7]

**Comment by ramnes** [comment]
Do you mean by "outputed" that it triggers messages? That's weird, because we have this: https://github.com/numberly/kubemen/blob/master/kubemen/app.py#L46

Maybe there's another field for diffs?

Depending on your needs, you could use `kubectl apply --dry-run=server` as a workaround.

**Comment by trubesv** [comment]
@shnups

**Comment by shnups** [comment]
Actually, i've just tested and both `kubectl diff` and `kubectl apply --dry-run=server` make kubemen generate "Update of Deployment" messages.

**Comment by trubesv** [comment]
![](https://i.ibb.co/TKFNhjK/1607326880.png)

**Comment by ramnes** [comment]
That's weird. Is the admission webhook configured with `sideEffects: NoneOnDryRun` as seen [here](https://github.com/numberly/kubemen/blob/master/deploy/kubemen.yaml#L18)? Does Kubemen receive the `dryRun` flag as handled [here](https://github.com/numberly/kubemen/blob/master/kubemen/app.py#L46)?

Documentation you might be interested in:
* https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#side-effects
* https://kubernetes.io/blog/2019/01/14/apiserver-dry-run-and-kubectl-diff/

**Comment by trubesv** [comment]
> Is the admission webhook configured with sideEffects: NoneOnDryRun

Yes

> Does Kubemen receive the dryRun flag

We'll check in more detail, thanks for docs

**Comment by trubesv** [comment]
Turns out we all need better eyes, the `dryRun` key is nested in the `request` one in the `AdmissionReview` object :eyes:

**Comment by ramnes** [comment]
Probably an API change in Kubernetes, and if so we should check both places.

**Comment by trubesv** [comment]
No, I think it was like that from the start and I misread the indentation when I implemented this.

Also it makes sense since we send back a `response` dict too.

**Comment by trubesv** [comment]
Fixed in https://github.com/numberly/kubemen/commit/824f8be83c929aa3c9ac38ab55795fcc61c5bb17
